sudo: required
addons:
  apt:
    packages:
    - quilt
    - parted
    - realpath
    - qemu-user-static
    - zerofree
    - pxz
    - zip
    - dosfstools
    - bsdtar
    - libcap2-bin
    - grep
    - rsync
    - xz-utils
install:
  # Workaround for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=857338
  - wget "http://archive.ubuntu.com/ubuntu/pool/main/d/debootstrap/debootstrap_1.0.78+nmu1ubuntu1_all.deb"
  - sudo dpkg --install debootstrap_1.0.78+nmu1ubuntu1_all.deb
script:
  - sudo ./prebuild.sh
before_deploy:
  # Workaround for https://github.com/travis-ci/dpl/issues/542
  - sudo chown $(id -u) build/deploy/*.zip
# deploy:
#   provider: releases
#   api_key:
#   file: build/deploy/*.zip
#   file_glob: true
#   skip_cleanup: true
#   on:
#     tags: true
