version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Install prerequisites
          command: apt install quilt gparted realpath qemu-user-static erofree pxz zip dosfstools bsdtar libcap2-bin grep rsync xz-utils
      - run:
          name: Install debootstrap
          command: |
            wget "http://archive.ubuntu.com/ubuntu/pool/main/d/debootstrap/debootstrap_1.0.78+nmu1ubuntu1_all.deb"
            sudo dpkg --install debootstrap_1.0.78+nmu1ubuntu1_all.deb
      - run:
          name: Build image
          command: sudo ./prebuild.sh
