version: 2
jobs:
  build:
    # machine: true
    docker:
      - image: buildpack-deps:xenial # primary container
        environment:
          ENV: CI
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install prerequisites
          command: apt update && apt install -y quilt gparted realpath qemu-user-static zerofree pxz zip dosfstools bsdtar libcap2-bin grep rsync xz-utils
      - run:
          name: Install debootstrap
          command: |
            wget "http://archive.ubuntu.com/ubuntu/pool/main/d/debootstrap/debootstrap_1.0.78+nmu1ubuntu1_all.deb"
            dpkg --install debootstrap_1.0.78+nmu1ubuntu1_all.deb
      - run:
          name: Build image
          command:  ./prebuild.sh
